### ISSUE TITLE
SDK changes filename if a space is in it 

### ISSUE THREAD

**Issue by ju-gu** [deepset-ai/deepset-cloud-sdk#114]
**Describe the bug**
When uploading files via the sdk, all spaces in the filenames are replaced with "%2520“ (see Screenshot). This makes it hard to read the names and is also a different behavior than uploading via the API/UI, where spaces are being kept.

**To Reproduce**
Upload file with spaces via the SDK

Expected behavior
Spaces should be kept

**Screenshots**
![image](https://github.com/deepset-ai/deepset-cloud-sdk/assets/87523290/613bb4d7-e156-4583-92d7-9e367c5b9c4e)

**Comment by ju-gu** [comment]
in addition a dash, "-", is converted in "%25E2%2580%2593"

**Comment by FHardow** [comment]
This comes from a double url encoding, just tested it.

**Comment by FHardow** [comment]
We quote the file name to make it safe for s3, [here](https://github.com/deepset-ai/deepset-cloud-sdk/blob/17ed2b4ec7661647f3b944f32c776131c8cd6375/deepset_cloud_sdk/_s3/upload.py#L61). 
We will need to adjust our file ingestion layer to dequote/decode these names again.

**Comment by wochinge** [comment]
seems we're double quoting actually

**Comment by wochinge** [comment]
SDK 0.34 fixes one part und the next deepset cloud release the other.
