### ISSUE TITLE
CLI not usable after installation on Mac

### ISSUE THREAD

**Issue by mathislucka** [deepset-ai/deepset-cloud-sdk#125]
**Describe the bug**
Following the instructions in the SDK docs, I installed with `pip install deepset-cloud-sdk`.
After the installation, I get the following error when trying to use the SDK `zsh: command not found: deepset-cloud`.

I'm sure it's just about adding this to PATH but that should be clear from the documentation.

**To Reproduce**

**Expected behavior**
Either that it works like in the documentation or that the documentation is updated to contain additional steps.

**Screenshots**

**Checklist**
- [ x] I added a label for the level of urgency of this bug (see definitions [here](https://www.notion.so/deepsetai/DC-processes-Bugs-and-Issues-79f7250be94b450a934296afd987a29a#4139a178336c439b8f52a99dde5e6b87))

**Comment by ArzelaAscoIi** [comment]
Did you manage to fix this? I guess its somehow related to the local setup. Would be helpful to understand what went wrong on your machine

**Comment by wochinge** [comment]
Tried and can't reproduce. 

Can you please provide additional information @mathislucka 
* Are you using Conda?
* Which Python version?
* Any special `.zshrc` config?
* Are you in a virtual environment / are you using some environment manager like pyenv / asdf?

**Comment by mathislucka** [comment]
I think we can close. I managed to fix by uninstalling completely and re-installing again. I was using conda py3.9 and nothing special in the .zshrc config. It just seems like the old installation broke somehow.
