### ISSUE TITLE
Receiving Invalid isoformat string error on upload

### ISSUE THREAD

**Issue by bglearning** [deepset-ai/deepset-cloud-sdk#155]
**Describe the bug**
When trying to upload a folder, receiving `ValueError: Invalid isoformat string: '2024-02-03T07:58:54.730474Z'` on [upload_sessions.py#L149](https://github.com/deepset-ai/deepset-cloud-sdk/blob/b16ed038e527e0ac968b7589955ed4f253e83d92/deepset_cloud_sdk/_api/upload_sessions.py#L149).

This might be not directly related to the sdk. Perhaps the API response format of the date changed?

**To Reproduce**
Run upload via the cli.

**Expected behavior**
Run without encountering this issue.

**Checklist**
- [x] I added a label for the level of urgency of this bug (see definitions [here](https://www.notion.so/deepsetai/DC-processes-Bugs-and-Issues-79f7250be94b450a934296afd987a29a#4139a178336c439b8f52a99dde5e6b87))

**Comment by sjrl** [comment]
Hey @bglearning does this PR https://github.com/deepset-ai/deepset-cloud-sdk/pull/156 fix your issue?

**Comment by bglearning** [comment]
Yup, it does!
