### ISSUE TITLE
Capability to upload files in nested folders

### ISSUE THREAD

**Issue by rjanjua** [deepset-ai/deepset-cloud-sdk#33]
**User Story**
As a developer
I want to upload files in a complex folder structure
So that I don't have to move files into a predefined structure

**Relevant Links**

**Acceptance Criteria**
- Files in a complex folder structure with multiple nested folders should be able to be uploaded through the `upload folder` method when called with a `recursive` param

**Task List**
- [ ] Task 2
- [ ] Task 3
- ...

**Comment by ArzelaAscoIi** [comment]
This is implemented by adding the `--recursive` argument to upload files method or `recursive` to the SDK :)
