### ISSUE TITLE
storing login credentials via `deepset-cloud-cli login` does not work for some users

### ISSUE THREAD

**Issue by ArzelaAscoIi** [deepset-ai/deepset-cloud-sdk#54]
@mathislucka could you add some details ?

**Comment by mathislucka** [comment]
I just tried and it now loads the credentials successfully. I did try a restart when it didn't work and that didn't help. No idea why it's working now.

**Comment by ArzelaAscoIi** [comment]
Okay, so lets close this for now and reopen of we can reproduce
